version: '3'
networks:
  my_network:
    driver: bridge
services:
  mariadb:
    container_name: mariadb
    networks:
      - my_network
    build: 
      context: .
      dockerfile: requirements/mariadb/Dockerfile
    env_file:
      - .env
  wordpress:
    container_name: wordpress
    depends_on:
      - mariadb
    networks:
      - my_network
    build:
      context: .
      dockerfile: requirements/wordpress/Dockerfile
    env_file:
      - .env
  nginx:
    container_name: nginx
    depends_on:
      - wordpress
    ports:
      - 443:443
    networks:
      - my_network
    build:
      context: .
      dockerfile: requirements/nginx/Dockerfile
    env_file:
      - .env