version: '3'
networks:
  my_network:

services:
  mariadb:
    container_name: mariadb
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - my_network
    build: 
      context: .
      dockerfile: requirements/mariadb/Dockerfile
    env_file:
      - .env
    restart: on-failure
    healthcheck:
      test: mysqladmin ping -h localhost
      interval: 15s
      timeout: 30s
      retries: 2
  wordpress:
    container_name: wordpress
    hostname: wordpress
    volumes:
      - wp_data:/var/www
    depends_on:
      mariadb:
        condition: service_healthy
    networks:
      - my_network
    build:
      context: .
      dockerfile: requirements/wordpress/Dockerfile
    env_file:
      - .env
    restart: on-failure
  nginx:
    container_name: nginx
    volumes:
      - wp_data:/var/www
    depends_on:
      - wordpress
    ports:
      - 443:443
    networks:
      - my_network
    build:
      context: .
      dockerfile: requirements/nginx/Dockerfile
    env_file:
      - .env
    restart: on-failure

volumes:
  wp_data:
    driver: local
    driver_opts:
      type: none
      device: /home/$USER/data/wp
      o: bind
  db_data:
    driver: local
    driver_opts:
      type: none
      device: /home/$USER/data/mariadb
      o: bind